development:
  adapter:    postgresql
  host:       localhost
  database:   mgyt_development
  timeout:    5432
  encoding:   utf8
  port:       5432
  pool:       7
  username:   mariusionutpop
  password:   barcelona

test:
  adapter:    postgresql
  host:       localhost
  database:   mgyt_test
  timeout:    5432
  encoding:   utf8
  port:       5432
  pool:       5
  username:   mariusionutpop
  password:   barcelona
