development:
  adapter:    postgresql
  host:       localhost
  database:   is_development
  timeout:    5433
  encoding:   utf8
  port:       5433
  pool:       5
  username:   postgres
  password:   postgres

test:
  adapter:    postgresql
  host:       localhost
  database:   is_test
  timeout:    5433
  encoding:   utf8
  port:       5433
  pool:       5
  username:   postgres
  password:   postgres