export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_CATEGORIES_ERROR = 'RECEIVE_CATEGORIES_ERROR';

export const REQUEST_SUB_CATEGORIES = 'REQUEST_SUB_CATEGORIES';
export const RECEIVE_SUB_CATEGORIES = 'RECEIVE_SUB_CATEGORIES';
export const RECEIVE_SUB_CATEGORIES_ERROR = 'RECEIVE_SUB_CATEGORIES_ERROR';

export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const RECEIVE_ITEMS_ERROR = 'RECEIVE_ITEMS_ERROR';

export const REQUEST_ITEM = 'REQUEST_ITEM';
export const RECEIVE_ITEM = 'RECEIVE_ITEM';
export const RECEIVE_ITEM_ERROR = 'RECEIVE_ITEM_ERROR';

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REQUEST_ADD_ITEM_BASKET = 'REQUEST_ADD_ITEM_BASKET';
export const SUCCESS_ADD_ITEM_BASKET = 'SUCCESS_ADD_ITEM_BASKET';
export const ERROR_ADD_ITEM_BASKET = 'ERROR_ADD_ITEM_BASKET';

export const REQUEST_REMOVE_ITEM_BASKET = 'REQUEST_REMOVE_ITEM_BASKET';
export const SUCCESS_REMOVE_ITEM_BASKET = 'SUCCESS_REMOVE_ITEM_BASKET';
export const ERROR_REMOVE_ITEM_BASKET = 'ERROR_REMOVE_ITEM_BASKET';

export const REQUEST_DELETE_ITEM_BASKET = 'REQUEST_DELETE_ITEM_BASKET';
export const SUCCESS_DELETE_ITEM_BASKET = 'SUCCESS_DELETE_ITEM_BASKET';
export const ERROR_DELETE_ITEM_BASKET = 'ERROR_DELETE_ITEM_BASKET';

export const REQUEST_ITEMS_BASKET = 'REQUEST_ITEMS_BASKET';
export const RECEIVE_ITEMS_BASKET = 'RECEIVE_ITEMS_BASKET';
export const RECEIVE_ITEMS_BASKET_ERROR = 'RECEIVE_ITEMS_BASKET_ERROR';

export const CLEAR_ERROR = 'CLEAR_ERROR';
