export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_CATEGORIES_ERROR = 'RECEIVE_CATEGORIES_ERROR';

export const REQUEST_SUB_CATEGORIES = 'REQUEST_SUB_CATEGORIES';
export const RECEIVE_SUB_CATEGORIES = 'RECEIVE_SUB_CATEGORIES';
export const RECEIVE_SUB_CATEGORIES_ERROR = 'RECEIVE_SUB_CATEGORIES_ERROR';

export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';
export const RECEIVE_ITEMS_ERROR = 'RECEIVE_ITEMS_ERROR';

export const REQUEST_ITEM = 'REQUEST_ITEM';
export const RECEIVE_ITEM = 'RECEIVE_ITEM';
export const RECEIVE_ITEM_ERROR = 'RECEIVE_ITEM_ERROR';

export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const CLEAR_ERROR = 'CLEAR_ERROR';
